/**
 * This file was auto-generated by Fern from our API Definition.
 */
package api.resources.v2.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum V2ChatRequestSafetyMode {
    CONTEXTUAL("CONTEXTUAL"),

    STRICT("STRICT"),

    OFF("OFF");

    private final String value;

    V2ChatRequestSafetyMode(String value) {
        this.value = value;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
