/**
 * This file was auto-generated by Fern from our API Definition.
 */
package api.types;

import com.cohere.api.core.ObjectMappers;
import com.cohere.api.types.ChatToolCallDeltaEventDeltaToolCallFunction;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = ChatToolCallDeltaEventDeltaToolCall.Builder.class)
public final class ChatToolCallDeltaEventDeltaToolCall {
    private final Optional<ChatToolCallDeltaEventDeltaToolCallFunction> function;

    private final Map<String, Object> additionalProperties;

    private ChatToolCallDeltaEventDeltaToolCall(
            Optional<ChatToolCallDeltaEventDeltaToolCallFunction> function, Map<String, Object> additionalProperties) {
        this.function = function;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("function")
    public Optional<ChatToolCallDeltaEventDeltaToolCallFunction> getFunction() {
        return function;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ChatToolCallDeltaEventDeltaToolCall
                && equalTo((ChatToolCallDeltaEventDeltaToolCall) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ChatToolCallDeltaEventDeltaToolCall other) {
        return function.equals(other.function);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.function);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<ChatToolCallDeltaEventDeltaToolCallFunction> function = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ChatToolCallDeltaEventDeltaToolCall other) {
            function(other.getFunction());
            return this;
        }

        @JsonSetter(value = "function", nulls = Nulls.SKIP)
        public Builder function(Optional<ChatToolCallDeltaEventDeltaToolCallFunction> function) {
            this.function = function;
            return this;
        }

        public Builder function(ChatToolCallDeltaEventDeltaToolCallFunction function) {
            this.function = Optional.of(function);
            return this;
        }

        public ChatToolCallDeltaEventDeltaToolCall build() {
            return new ChatToolCallDeltaEventDeltaToolCall(function, additionalProperties);
        }
    }
}
