/**
 * This file was auto-generated by Fern from our API Definition.
 */
package api.types;

import com.cohere.api.core.ObjectMappers;
import com.cohere.api.types.ChatCitation;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

import java.util.*;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = ChatCitationGenerationEvent.Builder.class)
public final class ChatCitationGenerationEvent implements IChatStreamEvent {
    private final List<ChatCitation> citations;

    private final Map<String, Object> additionalProperties;

    private ChatCitationGenerationEvent(List<ChatCitation> citations, Map<String, Object> additionalProperties) {
        this.citations = citations;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Citations for the generated reply.
     */
    @JsonProperty("citations")
    public List<ChatCitation> getCitations() {
        return citations;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ChatCitationGenerationEvent && equalTo((ChatCitationGenerationEvent) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ChatCitationGenerationEvent other) {
        return citations.equals(other.citations);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.citations);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private List<ChatCitation> citations = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ChatCitationGenerationEvent other) {
            citations(other.getCitations());
            return this;
        }

        @JsonSetter(value = "citations", nulls = Nulls.SKIP)
        public Builder citations(List<ChatCitation> citations) {
            this.citations.clear();
            this.citations.addAll(citations);
            return this;
        }

        public Builder addCitations(ChatCitation citations) {
            this.citations.add(citations);
            return this;
        }

        public Builder addAllCitations(List<ChatCitation> citations) {
            this.citations.addAll(citations);
            return this;
        }

        public ChatCitationGenerationEvent build() {
            return new ChatCitationGenerationEvent(citations, additionalProperties);
        }
    }
}
