/**
 * This file was auto-generated by Fern from our API Definition.
 */
package api.types;

import com.cohere.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = ChatContentDeltaEventDeltaMessageContent.Builder.class)
public final class ChatContentDeltaEventDeltaMessageContent {
    private final Optional<String> text;

    private final Map<String, Object> additionalProperties;

    private ChatContentDeltaEventDeltaMessageContent(Optional<String> text, Map<String, Object> additionalProperties) {
        this.text = text;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("text")
    public Optional<String> getText() {
        return text;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ChatContentDeltaEventDeltaMessageContent
                && equalTo((ChatContentDeltaEventDeltaMessageContent) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ChatContentDeltaEventDeltaMessageContent other) {
        return text.equals(other.text);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.text);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> text = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ChatContentDeltaEventDeltaMessageContent other) {
            text(other.getText());
            return this;
        }

        @JsonSetter(value = "text", nulls = Nulls.SKIP)
        public Builder text(Optional<String> text) {
            this.text = text;
            return this;
        }

        public Builder text(String text) {
            this.text = Optional.of(text);
            return this;
        }

        public ChatContentDeltaEventDeltaMessageContent build() {
            return new ChatContentDeltaEventDeltaMessageContent(text, additionalProperties);
        }
    }
}
