/**
 * This file was auto-generated by Fern from our API Definition.
 */
package api.types;

import com.cohere.api.core.ObjectMappers;
import com.cohere.api.types.EmbedJob;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

import java.util.*;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = ListEmbedJobResponse.Builder.class)
public final class ListEmbedJobResponse {
    private final Optional<List<EmbedJob>> embedJobs;

    private final Map<String, Object> additionalProperties;

    private ListEmbedJobResponse(Optional<List<EmbedJob>> embedJobs, Map<String, Object> additionalProperties) {
        this.embedJobs = embedJobs;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("embed_jobs")
    public Optional<List<EmbedJob>> getEmbedJobs() {
        return embedJobs;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListEmbedJobResponse && equalTo((ListEmbedJobResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListEmbedJobResponse other) {
        return embedJobs.equals(other.embedJobs);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.embedJobs);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<EmbedJob>> embedJobs = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListEmbedJobResponse other) {
            embedJobs(other.getEmbedJobs());
            return this;
        }

        @JsonSetter(value = "embed_jobs", nulls = Nulls.SKIP)
        public Builder embedJobs(Optional<List<EmbedJob>> embedJobs) {
            this.embedJobs = embedJobs;
            return this;
        }

        public Builder embedJobs(List<EmbedJob> embedJobs) {
            this.embedJobs = Optional.of(embedJobs);
            return this;
        }

        public ListEmbedJobResponse build() {
            return new ListEmbedJobResponse(embedJobs, additionalProperties);
        }
    }
}
