/**
 * This file was auto-generated by Fern from our API Definition.
 */
package api.types;

import com.cohere.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

import java.util.*;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = ToolMessage.Builder.class)
public final class ToolMessage {
    private final Optional<List<ToolResult>> toolResults;

    private final Map<String, Object> additionalProperties;

    private ToolMessage(Optional<List<ToolResult>> toolResults, Map<String, Object> additionalProperties) {
        this.toolResults = toolResults;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("tool_results")
    public Optional<List<ToolResult>> getToolResults() {
        return toolResults;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ToolMessage && equalTo((ToolMessage) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ToolMessage other) {
        return toolResults.equals(other.toolResults);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.toolResults);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<ToolResult>> toolResults = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ToolMessage other) {
            toolResults(other.getToolResults());
            return this;
        }

        @JsonSetter(value = "tool_results", nulls = Nulls.SKIP)
        public Builder toolResults(Optional<List<ToolResult>> toolResults) {
            this.toolResults = toolResults;
            return this;
        }

        public Builder toolResults(List<ToolResult> toolResults) {
            this.toolResults = Optional.of(toolResults);
            return this;
        }

        public ToolMessage build() {
            return new ToolMessage(toolResults, additionalProperties);
        }
    }
}
