/**
 * This file was auto-generated by Fern from our API Definition.
 */
package api.types;

import com.cohere.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

import java.util.*;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = ToolResult.Builder.class)
public final class ToolResult {
    private final ToolCall call;

    private final List<Map<String, Object>> outputs;

    private final Map<String, Object> additionalProperties;

    private ToolResult(ToolCall call, List<Map<String, Object>> outputs, Map<String, Object> additionalProperties) {
        this.call = call;
        this.outputs = outputs;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("call")
    public ToolCall getCall() {
        return call;
    }

    @JsonProperty("outputs")
    public List<Map<String, Object>> getOutputs() {
        return outputs;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ToolResult && equalTo((ToolResult) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ToolResult other) {
        return call.equals(other.call) && outputs.equals(other.outputs);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.call, this.outputs);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static CallStage builder() {
        return new Builder();
    }

    public interface CallStage {
        _FinalStage call(ToolCall call);

        Builder from(ToolResult other);
    }

    public interface _FinalStage {
        ToolResult build();

        _FinalStage outputs(List<Map<String, Object>> outputs);

        _FinalStage addOutputs(Map<String, Object> outputs);

        _FinalStage addAllOutputs(List<Map<String, Object>> outputs);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements CallStage, _FinalStage {
        private ToolCall call;

        private List<Map<String, Object>> outputs = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @Override
        public Builder from(ToolResult other) {
            call(other.getCall());
            outputs(other.getOutputs());
            return this;
        }

        @Override
        @JsonSetter("call")
        public _FinalStage call(ToolCall call) {
            this.call = call;
            return this;
        }

        @Override
        public _FinalStage addAllOutputs(List<Map<String, Object>> outputs) {
            this.outputs.addAll(outputs);
            return this;
        }

        @Override
        public _FinalStage addOutputs(Map<String, Object> outputs) {
            this.outputs.add(outputs);
            return this;
        }

        @Override
        @JsonSetter(value = "outputs", nulls = Nulls.SKIP)
        public _FinalStage outputs(List<Map<String, Object>> outputs) {
            this.outputs.clear();
            this.outputs.addAll(outputs);
            return this;
        }

        @Override
        public ToolResult build() {
            return new ToolResult(call, outputs, additionalProperties);
        }
    }
}
