/**
 * This file was auto-generated by Fern from our API Definition.
 */
package api.types;

import com.cohere.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = ToolCall.Builder.class)
public final class ToolCall {
    private final String name;

    private final Map<String, Object> parameters;

    private final Map<String, Object> additionalProperties;

    private ToolCall(String name, Map<String, Object> parameters, Map<String, Object> additionalProperties) {
        this.name = name;
        this.parameters = parameters;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Name of the tool to call.
     */
    @JsonProperty("name")
    public String getName() {
        return name;
    }

    /**
     * @return The name and value of the parameters to use when invoking a tool.
     */
    @JsonProperty("parameters")
    public Map<String, Object> getParameters() {
        return parameters;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ToolCall && equalTo((ToolCall) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ToolCall other) {
        return name.equals(other.name) && parameters.equals(other.parameters);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.name, this.parameters);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static NameStage builder() {
        return new Builder();
    }

    public interface NameStage {
        _FinalStage name(String name);

        Builder from(ToolCall other);
    }

    public interface _FinalStage {
        ToolCall build();

        _FinalStage parameters(Map<String, Object> parameters);

        _FinalStage putAllParameters(Map<String, Object> parameters);

        _FinalStage parameters(String key, Object value);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements NameStage, _FinalStage {
        private String name;

        private Map<String, Object> parameters = new LinkedHashMap<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @Override
        public Builder from(ToolCall other) {
            name(other.getName());
            parameters(other.getParameters());
            return this;
        }

        /**
         * <p>Name of the tool to call.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @Override
        @JsonSetter("name")
        public _FinalStage name(String name) {
            this.name = name;
            return this;
        }

        /**
         * <p>The name and value of the parameters to use when invoking a tool.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @Override
        public _FinalStage parameters(String key, Object value) {
            this.parameters.put(key, value);
            return this;
        }

        /**
         * <p>The name and value of the parameters to use when invoking a tool.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @Override
        public _FinalStage putAllParameters(Map<String, Object> parameters) {
            this.parameters.putAll(parameters);
            return this;
        }

        @Override
        @JsonSetter(value = "parameters", nulls = Nulls.SKIP)
        public _FinalStage parameters(Map<String, Object> parameters) {
            this.parameters.clear();
            this.parameters.putAll(parameters);
            return this;
        }

        @Override
        public ToolCall build() {
            return new ToolCall(name, parameters, additionalProperties);
        }
    }
}
